### ISSUE TITLE
Pre-submission checklist

### ISSUE THREAD

**Issue by gciatto** [pikalab-unibo/ski-jlc-cilc-extension-2022#2]
- [ ] use `lncs` style
- [ ] mention multiple experiments in the intro
- [ ] rephrase the abstract
- [ ] extend the conclusions according to #1
